CC = gcc
CFLAGS = -Wall -Werror -Wextra -pedantic -g

todo_api_0: todo_api_0.c
	$(CC) $(CFLAGS) -o todo_api_0 todo_api_0.c

todo_api_1: todo_api_1.c
	$(CC) $(CFLAGS) -o todo_api_1 todo_api_1.c

clean:
	rm -f todo_api_0 todo_api_1

.PHONY: clean
